project:
  type: website
  output-dir: docs

website:
  title: "Tahana Akram"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects
      
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/tahanaakram/
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/akramt24
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



